#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"

volumes:
  static-files:
    driver: local
  postgres:
    driver: local
    
services:
    db:
      image: postgres:11
      volumes:
        - postgres:/var/lib/postgresql/data/pgdata
      env_file:
        - ./environment/.env

    webserver:
      image: nginx:1.15
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - webapp
      volumes:
        - ./webserver/nginx.tmpl:/etc/nginx/conf.d/nginx.tmpl
        - ./webserver/localhost.crt:/etc/ssl/certs/localhost.crt
        - ./webserver/localhost.key:/etc/ssl/private/localhost.key
        - static-files:/srv/static-files
      env_file:
        - ./environment/.env
      command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.tmpl > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

    webapp:
      build:
        context: webapp
      volumes:
        - ./webapp:/srv/myproject
        - static-files:/srv/static-files
      expose:
        - "3031"
      ports:
        - "8000:8000"
        - "8001:8001"
      depends_on:
        - db
      env_file:
        - ./environment/.env
